### ISSUE TITLE
grep does not work on Mac

### ISSUE THREAD

**Issue by KevinSjoberg** [adsr/mle#25]
Whenever I try to grep for something using `M-q`, it just returns an empty buffer and the mode is set to `mle-menu`. Grepping for the exact same thing under Linux returns the expected results.

Don't seem to yield any errors so not really sure how to debug it.

**Comment by KevinSjoberg** [comment]
Turns out it's due to the difference in GNU version of `grep` vs the BSD one. The `-P` flag (for Perl regular expressions) does not exist in the BSD version. Both versions of `grep` does have the `-E` for extended regular expression.

Not sure what the right approach is here. We could remove `-P` in favor for `-E` (although they're not equivalent). We could also let the user provide their own arguments (don't know how much work that would require) or we could assume the user have something like `ripgrep` instead, that is unified across platforms.

**Comment by adsr** [comment]
Hi Kevin, good catch. I am a big fan of PCRE so I hard-coded my own preference here (`grep -P`) but as you point out it is not portable.

Overriding the default grep command is possible with a custom mode:

```
mle -K 'custom_mode,,1' -k 'cmd_grep,M-q,echo replace me %s 2>/dev/null' -n custom_mode
```

These flags can be placed in `.mlerc` to make them permanent.

That said I agree the editor should make an attempt to pick a sensible default, so on macOS it will now use `-E` instead of `-P`: 408a1a4c4f2c63b13c3a8f5d752bdef28960d46a
