### ISSUE TITLE
can you mark 1.7.1 as latest release?

### ISSUE THREAD

**Issue by chenrui333** [adsr/mle#78]
👋 it looks like 1.7.1 is the latest release, but just lack the release notes or designation for it (currently it still points to 1.5.0). With that being said, can you mark it as latest release? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/131513

**Comment by adsr** [comment]
Will do. I tagged 1.7.1 but then realized I should probably test it on a few distros first. I found one test failure on Alpine due to BusyBox tree working differently than GNU tree. I'll cut a proper release for 1.7.2 in the next few days after I do some more testing.

Thanks for the homebrew package by the way.

**Comment by chenrui333** [comment]
np at all, and good to know about the plan, gonna close that PR and wait for the 1.7.2 release then :)

**Comment by adsr** [comment]
@chenrui333 I just cut v1.7.2. Thank you again.

**Comment by chenrui333** [comment]
thanks, we got it handled in here, https://github.com/Homebrew/homebrew-core/pull/131966 🍻
